id: I1EB898D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:00:24+00:00'
last_modified: '2022-06-07T18:32:46.591550+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03697
  title: བློ་རིག་གི་རྣམ་བཞག་ཉུང་གསལ་ལེགས་བཤད་གསེར་གྱི་ཕྲེང་མཛེས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    733D:
      image_group_id: I00KG03778
      title: ''
      total_pages: 138
      order: 1
      base_file: 733D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
