id: P003232
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:49:06.872369
source_metadata:
  id: bdr:W00KG03697
  title: བློ་རིག་གི་རྣམ་བཞག་ཉུང་གསལ་ལེགས་བཤད་གསེར་གྱི་ཕྲེང་མཛེས
  author: ''
  volumes:
    1b4a755b0b76452786f7e52e31db08d7:
      image_group_id: I00KG03778
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
