id: P003232
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03697
  title: བློ་རིག་གི་རྣམ་བཞག་ཉུང་གསལ་ལེགས་བཤད་གསེར་གྱི་ཕྲེང་མཛེས
  author: ''
  volumes:
    1b4a755b0b76452786f7e52e31db08d7:
      image_group_id: I00KG03778
      title: ''
      volume_number: 1
      total_pages: 138
